# This is a basic workflow that is manually triggered

name: Release new version

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        description: 'Version to upgrade'
        default: 'World'
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
    # Runs a single command using the runners shell
    - name: Clone project
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Tag project
      run: echo Tagging project ${{ inputs.version }} && git tag ${{ inputs.version }}
    - name: Push tag
      run: git push origin ${{ inputs.version }}
